### ISSUE TITLE
Can seqQscorer be used for plant species?

### ISSUE THREAD

**Issue by zhaijj** [salbrec/seqQscorer#1]
Hi,

seqQscorer is a very useful tool for quality control of NGS data. I wonder if seqQscorer is suitable for plant species.

Thank you!

**Comment by salbrec** [comment]
Hi Jingjing,

thanks for this question. Basically, there was no availability of quality-labeled NGS data for plant species and therefore it was not possible to train a corresponding specialized model for seqQscorer, unfortunately. However, as shown in our article, to some extent the approach performs well even if the models were trained on a different species. This was working well in particular for ChIP-seq (Fig. 5A). So it could be worth it to try seqQscorer on plant data. I recommend to use the generic model (default settings) on plant samples, if you have some... In best case, if possible, one could manually check on a few samples if the ordering by the seqQscorer score (probability) fits the data.

Best wishes,
Steffen
